package vn.truongngo.apartcom.one.service.admin.domain.user;

import lombok.Getter;
import vn.truongngo.apartcom.one.lib.common.utils.lang.Assert;
import vn.truongngo.apartcom.one.service.admin.domain.abac.policy.Scope;
import vn.truongngo.apartcom.one.service.admin.domain.role.RoleId;

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Represents the set of roles a user holds within a specific scope+org context.
 * Child entity of User — not an aggregate root.
 *
 * Examples:
 *   { scope=ADMIN,    orgId=null,        roleIds=[ADMIN] }
 *   { scope=TENANT,   orgId="company-z", roleIds=[TENANT_ADMIN] }
 *   { scope=RESIDENT, orgId="unit-10b",  roleIds=[RESIDENT] }
 */
@Getter
public class RoleContext {

    private final Long id;           // null for new (auto-generated by persistence)
    private final Scope scope;
    private final String orgId;      // null for ADMIN scope (no org affiliation)
    private final Set<RoleId> roleIds;

    private RoleContext(Long id, Scope scope, String orgId, Set<RoleId> roleIds) {
        this.id      = id;
        this.scope   = scope;
        this.orgId   = orgId;
        this.roleIds = new HashSet<>(roleIds != null ? roleIds : Set.of());
    }

    public static RoleContext create(Scope scope, String orgId, Set<RoleId> roleIds) {
        Assert.notNull(scope, "scope is required");
        return new RoleContext(null, scope, orgId, roleIds);
    }

    public static RoleContext reconstitute(Long id, Scope scope, String orgId, Set<RoleId> roleIds) {
        return new RoleContext(id, scope, orgId, roleIds);
    }

    public boolean matchesScope(Scope scope, String orgId) {
        return this.scope == scope && Objects.equals(this.orgId, orgId);
    }

    // Package-private — only User aggregate may mutate role membership
    void addRole(RoleId roleId) {
        roleIds.add(roleId);
    }

    void removeRole(RoleId roleId) {
        roleIds.removeIf(r -> r.getValue().equals(roleId.getValue()));
    }
}
